import type { Metadata } from "next";
import "./globals.css";
import { Lato, Prata } from "next/font/google";
import DesktopNavbar from "@/components/desktopNavbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/providers/themeProviders";
import PageTransition from "@/components/pageTransition";
import StoreProvider from "@/components/providers/storeProvider";
import { CartContextProvider } from "@/components/providers/cartProvider";

const prata = Prata({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-prata",
});
const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: {
    template: "%s – Brushscape",
    default: "Brushscape",
  },
};
// description: "Generated by create next app",

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prata.variable} ${lato.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <CartContextProvider>
              <DesktopNavbar />
              <PageTransition>{children}</PageTransition>
              <Footer />
            </CartContextProvider>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
