import type { Metadata } from "next";
import { Inter, Lato, Prata } from "next/font/google";
import "./globals.css";
import DesktopNavbar from "@/components/desktopNavbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/providers/themeProviders";

const inter = Inter({ subsets: ["latin"] });
const prata = Prata({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-prata",
});
const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prata.variable} ${lato.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DesktopNavbar />
          <main className="relative flex flex-col items-center justify-start w-full">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
